// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOpp58zP2DXv-nS3dGbybenR19_hmo8qg',
    appId: '1:716988093767:web:7409e6f0501ca41db0e862',
    messagingSenderId: '716988093767',
    projectId: 'ludo-fbd23',
    authDomain: 'ludo-fbd23.firebaseapp.com',
    storageBucket: 'ludo-fbd23.appspot.com',
    measurementId: 'G-LYRCV4DF7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2dWPFk9usXOWq1DNbgLY-WCnnzAWlUkI',
    appId: '1:716988093767:android:79e57af55337fa3fb0e862',
    messagingSenderId: '716988093767',
    projectId: 'ludo-fbd23',
    storageBucket: 'ludo-fbd23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZClfrCJBUyj84TIo3aQWT68vFBSMvsG8',
    appId: '1:716988093767:ios:bf8888371287a2a6b0e862',
    messagingSenderId: '716988093767',
    projectId: 'ludo-fbd23',
    storageBucket: 'ludo-fbd23.appspot.com',
    iosBundleId: 'com.obeckley.ludo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZClfrCJBUyj84TIo3aQWT68vFBSMvsG8',
    appId: '1:716988093767:ios:bf8888371287a2a6b0e862',
    messagingSenderId: '716988093767',
    projectId: 'ludo-fbd23',
    storageBucket: 'ludo-fbd23.appspot.com',
    iosBundleId: 'com.obeckley.ludo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOpp58zP2DXv-nS3dGbybenR19_hmo8qg',
    appId: '1:716988093767:web:9924d9e0a08abf6fb0e862',
    messagingSenderId: '716988093767',
    projectId: 'ludo-fbd23',
    authDomain: 'ludo-fbd23.firebaseapp.com',
    storageBucket: 'ludo-fbd23.appspot.com',
    measurementId: 'G-SZCRKPGHK6',
  );
}
